### ISSUE TITLE
Work on map

### ISSUE THREAD

**Issue by brandynh** [brandynh/Thirstys#10]
work on getting map displayed on bottom and map marker

**Comment by wmsimien** [comment]
Map working w/ marker of location being placed on map.  Also, switched out brewery api for tomtom fuzzy search appi (works much better; but, response data is different).  Also, have the map scrolling to the bottom of the window; need to talk about that.  Working on saving search history; but, working on it from the perspective that users will be able to save their top five (or three) on a menu component for recall.

**Comment by wmsimien** [comment]
Also, have the url working on the cards and added a button (Map It) to generate the map.  Noticed that the urls from the API are not fully qualified and working on  code to fix that by adding the https:// and/or htpps://www. to the url.
